%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/adeshkadambi/Desktop/sz_clustering/fKH14_20170710_003235.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/04/15 16:47:05

%% Initialize variables.
filename = '/Users/adeshkadambi/Desktop/sz_clustering/fKH14_20170710_003235.csv';
delimiter = ',';
startRow = 10;

%% Format for each line of text:
%   column3: double (%f)
%	column5: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%f%*s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
fKH1420170710003235 = table(dataArray{1:end-1}, 'VariableNames', {'VarName3','VarName5'})

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;